--Create DATABASE DAPPERDOTNETCORE
USE DAPPERDOTNETCORE

--CREATE TABLE CATEGORIES
--(
--ID INT PRIMARY KEY IDENTITY (1,1),
--NAME NVARCHAR(50),
--STATUS BIT


--);
--CREATE TABLE PRODUCTS(
--ID INT PRIMARY KEY IDENTITY(1,1),
--TITLE NVARCHAR(50),
--PRICE DECIMAL(18,2),
--COVERIMAGE NVARCHAR(MAX),
--CITY NVARCHAR(50),
--DISTRICT NVARCHAR(50),
--ADDRESS NVARCHAR(500),
--DESCRIPTION NVARCHAR(1000),
--PRODUCTCATEGORY INT

--);

--CREATE TABLE PRODUCTDETAILS
--(
--ID INT PRIMARY KEY IDENTITY(1,1),
--PRODUCTSIZE INT,
--BEDROOMCOUNT TINYINT,
--BATHCOUNT TINYINT,
--ROOMCOUNT TINYINT,
--GARAGESIZE TINYINT,
--BUILDYEAR CHAR(4),
--PRICE DECIMAL(18,2),
--LOCATION NVARCHAR(MAX),
--VIDEOURL NVARCHAR(MAX),

--PRODUCTID INT 
--);

--CREATE TABLE CLIENT
--(
--ID INT PRIMARY KEY IDENTITY(1,1),
--NAME NVARCHAR(50),
--TITLE NVARCHAR(50),
--COMMENT NVARCHAR(MAX)
--);


--CREATE TABLE EMPLOYEE
--(
--ID INT PRIMARY KEY IDENTITY(1,1),
--NAME NVARCHAR(50),
--TITLE NVARCHAR(50),
--MAIL NVARCHAR(50),
--PHONENUMBER NVARCHAR(11),
--IMAGEURL NVARCHAR(MAX),
--STATUS BIT
--);